sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
    - chefdk
    - libgecode-dev
    - coreutils

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  global:
  - USE_SYSTEM_GECODE=true
  matrix:
  - INSTANCE=gemrc-global-ubuntu-1404
  - INSTANCE=gemrc-global-ubuntu-1604
  - INSTANCE=gemrc-global-centos-6
  - INSTANCE=gemrc-global-centos-7
  - INSTANCE=gemrc-local-ubuntu-1404
  - INSTANCE=gemrc-local-ubuntu-1604
  - INSTANCE=gemrc-local-centos-6
  - INSTANCE=gemrc-local-centos-7
  - INSTANCE=gemrc-explicit-path-ubuntu-1404
  - INSTANCE=gemrc-explicit-path-ubuntu-1604
  - INSTANCE=gemrc-explicit-path-centos-6
  - INSTANCE=gemrc-explicit-path-centos-7
  - INSTANCE=gemrc-local-merge-ubuntu-1404
  - INSTANCE=gemrc-local-merge-ubuntu-1604
  - INSTANCE=gemrc-local-merge-centos-6
  - INSTANCE=gemrc-local-merge-centos-7
  - INSTANCE=bundle-config-ubuntu-1404
  - INSTANCE=bundle-config-ubuntu-1604
  - INSTANCE=bundle-config-centos-6
  - INSTANCE=bundle-config-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
